### ISSUE TITLE
Crash on Linux_x64

### ISSUE THREAD

**Issue by FelixResch** [MojoGG/AMC#1]
Normal Program start, no manga list loaded, loading icon stays, error dump

[16066:0918/095733:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[16066:0918/095733:ERROR:nw_shell.cc(335)] Error: Cannot find module 'anime-scraper'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at file:///tmp/.org.chromium.Chromium.naBN0Q/js/provider/kissanime.js:1:18
[16066:0918/095733:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'anime-scraper'", source: module.js (329)
[16066:0918/095734:INFO:CONSOLE(12450)] " "\u003Cdiv data-ui-view=\"\" class=\"ng-scope\"\u003E"", source: file:///tmp/.org.chromium.Chromium.naBN0Q/plugins/angular/angular.js (12450)
[16146:0918/095953:ERROR:channel.cc(305)] RawChannel read error (connection broken)
[16066:0918/100039:INFO:CONSOLE(192)] ""/js/bootstrap.min.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (192)
[16066:0918/100039:INFO:CONSOLE(192)] ""/js/moment.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (192)
[16066:0918/100039:INFO:CONSOLE(192)] ""/js/bootstrap-datetimepicker.min.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (192)
[16066:0918/100039:INFO:CONSOLE(192)] ""/js/bootstrap-filestyle.min.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (192)
[16066:0918/100039:INFO:CONSOLE(192)] ""/js/terminal.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (192)
[16066:0918/100040:INFO:CONSOLE(211)] ""Successfully loaded /js/bootstrap.min.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (211)
[16066:0918/100040:INFO:CONSOLE(211)] ""Successfully loaded /js/moment.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (211)
[16066:0918/100040:INFO:CONSOLE(211)] ""Successfully loaded /js/bootstrap-datetimepicker.min.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (211)
[16066:0918/100040:INFO:CONSOLE(211)] ""Successfully loaded /js/bootstrap-filestyle.min.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (211)
[16066:0918/100040:INFO:CONSOLE(211)] ""Successfully loaded /js/terminal.js"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (211)
[16066:0918/100046:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100046:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100046:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100046:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100047:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100050:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100053:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16066:0918/100056:INFO:CONSOLE(152)] ""Action State ok"", source: https://xjs-proxerread.rhcloud.com/xjs/xaction.js (152)
[16097:0918/100122:ERROR:channel.cc(305)] RawChannel read error (connection broken)
Parent failed to complete crash dump.

**Comment by ghost** [comment]
Should work now :+1:

**Comment by FelixResch** [comment]
AMC now apparently has missing dependencies
- underscore
- xml2js

[31510:1009/132256:ERROR:nw_shell.cc(335)] Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at file:///tmp/.org.chromium.Chromium.XSibfH/js/controller/anime/home.js:1:9
[31510:1009/132256:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'underscore'", source: module.js (329)
[31510:1009/132256:ERROR:nw_shell.cc(335)] Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at file:///tmp/.org.chromium.Chromium.XSibfH/js/provider/animeNewsNetwork.js:2:19
[31510:1009/132256:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'xml2js'", source: module.js (329)
[31510:1009/132256:INFO:CONSOLE(12450)] "", source: file:///tmp/.org.chromium.Chromium.XSibfH/plugins/angular/angular.js (12450)

**Comment by FelixResch** [comment]
Build log 

[build.txt](https://github.com/femoio/AMC/files/10740/build.txt)

**Comment by FelixResch** [comment]
commit 370da33a8cbea81e9a594cec7753ce5259228a93 works in WebStorms without errors

although with a lot of unnecessary logs

**Comment by ghost** [comment]
Should work now - Problem was nwjs builder didnt pack node modules. Now Node modules are included but building also takes a lot longer :grin:
